// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgotZ8AkxW-hWnacwK8TITGfhEkMrjSww',
    appId: '1:674046034853:web:391fcebaf229a475791e4c',
    messagingSenderId: '674046034853',
    projectId: 'ffood-18909',
    authDomain: 'ffood-18909.firebaseapp.com',
    storageBucket: 'ffood-18909.appspot.com',
    measurementId: 'G-NDW7N7FW42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzEbv8Fy236O51RF-Vh4K3av09YnY252k',
    appId: '1:674046034853:android:8264582ee33f21df791e4c',
    messagingSenderId: '674046034853',
    projectId: 'ffood-18909',
    storageBucket: 'ffood-18909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC49mF224GGpOxaBMuN2Hcjd4ixFkIpUkw',
    appId: '1:674046034853:ios:2ac391f40c5bcfef791e4c',
    messagingSenderId: '674046034853',
    projectId: 'ffood-18909',
    storageBucket: 'ffood-18909.appspot.com',
    iosClientId: '674046034853-t70nj7qpim7bi8tknuc9se2p3l7reog0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC49mF224GGpOxaBMuN2Hcjd4ixFkIpUkw',
    appId: '1:674046034853:ios:2ac391f40c5bcfef791e4c',
    messagingSenderId: '674046034853',
    projectId: 'ffood-18909',
    storageBucket: 'ffood-18909.appspot.com',
    iosClientId: '674046034853-t70nj7qpim7bi8tknuc9se2p3l7reog0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffood',
  );
}
